//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxWeather
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forecasts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forecasts()
        {
            this.Weather = new HashSet<Weather>();
        }
    
        public int id { get; set; }
        public int time { get; set; }
        public int temperature { get; set; }
        public int condition { get; set; }
    
        public virtual Conditions Conditions { get; set; }
        public virtual Time Time1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Weather> Weather { get; set; }
    }
}
