//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaxWeather
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Weather()
        {
            this.Forecasts = new HashSet<Forecasts>();
        }
    
        public int id { get; set; }
        public System.DateTime day { get; set; }
        public int city { get; set; }
        public int pressure { get; set; }
        public int humidity { get; set; }
        public int wind { get; set; }
        public int speed { get; set; }
        public int uv { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Wind Wind1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forecasts> Forecasts { get; set; }
    }
}
